language: perl
sudo: false
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"

before_install:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov
  - cpanm --quiet --notest --skip-satisfied --installdeps --with-recommend .

script:
  - perl Build.PL
  - ./Build build
  - cover -test

after_success:
  - cover -report codecov
