language: perl
sudo: false
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"

before_install:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov

script:
  - perl Build.PL && ./Build build
  - prove -r xt
  - cover -test

after_success:
  - cover -report codecov

notifications:
  slack:
    - secure: "GhY8aQJDcUuYLI0Twc/2RdJJdcOnQzY0FM85PsqCqcDJ4aPqCQRGjXEQS3Mb2PFqn0tlGFNUGxBYY5vrqetCC6Whhvh+xDqb39bae5LjAqDQG7wr8cR6nK/4CWAZ28BUJfXh8nezpU3/AIHSRqfKRyLetQctS70i9xSHTTm3MkvAZB4Vf8d9SJz3L3fT6WDbHnHQhG4XuLxSgX1wFiXnxTCI2qtEsqSOnz6+n4W8BowdjKuvaXwje3Ei9qznb3b3omxKXp7QYuhMMsq0b0wU8x2lhJYK6H3XMsgh4t2i7xdqfgm8GNjSZvUKGPnL10neOCzedWPLf6e1qAtFYOn/SeHS8/QxJ7ud3/m0Xp54BP6QDXF4zJckzapqBzaUvSCRUuhwzALcR5Rrly67oJlCskNKhsacrhBtjnb0a0JxYosyFk5O3HLGCB+QhbCpQdj8aql58Rv3lH9DABqyj56C33tbjyEDpMm5VFDGzWmMvKTzBGSj/6St9jEeLI3CnxtOqLDwNVbIsnjv9bbNRGOZuuA2Y7cjEtB/CMHKwJvldg7Dy+gRLNWN9ehEEGDxU0qerjl17qIi+sASjQY/OGFt4Bl6v/e1xje073H+beNy1Gp4E7W+Y4hFP7K3apSDcvE73Fr3y0wOsUx9mKyClP3RL3DWTpLZN5Gape8IZSo40ek="
