language: perl
sudo: false
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
  - "5.30"
  
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V

install:
  - cpan-install --deps
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov

script:
  - perl Build.PL && ./Build build
  - prove -r xt
  - cover -test

after_success:
  - cover -report codecov

notifications:
  slack:
    - secure: "Q1s+4eKv3vAMkCahW/4fHJl4VJ00ZjG6I7lrypmQrKNWSSRH4DoYjPRTd4+lRM7MLMRAzmv5jED2ekREqAiJSPFDJHvWavEhXiZOtBQMCSHysoXQsEfmLCPBxq/z1QjTAsi4qCgbT30eriMLdDbInG3GlT5UQCGbxDuS3Ip/Av/mFOX/6Xrp0hzE7GfKTbwf8N+ZMwifrrctB65H0DeGfjZjthalgK8ZBQ9oOHS6v8iuWznA2my+CS9D/fBZF4MIZuqrm9Glq88nu6kLBwkBRJ29YuIF6ec0I8JS2NBQQE4SiYhSfA7EpyYfbNSgovMZkyDj+6lESmHN4HQgqrbETmi6v+OvQZ6OXacXb7yUow6nAHC8QQFi2x1ZGovetdWDkWF5svjPc+eWbzDAt2XchzdeEfykgkd+k2fcBaVP4UeudRlRcIgpg3AwNM2hLdkQsqcaRxrVTmbfGOee/XhvMGMI07f5ffM5+tJG4I0vw2VHIVm1jdAwU4ZPvbtpn3N53auwH5iSBHmrgxY4eCmmwpZVkr8Qac1AZs7lRDEXfrcXsYaSf/SnO5Fwdo03ueqR6r3YyCWyVnTYAfvJDR4ECdkXqwU8cpIaoTTJ+7c/nEZZPYG7rm/MmNl90XaRtKZGi2vvKYFc85DGBYPR9VdmYbtEW9TbHLrO2COAI4BXO3g="
